set_property -dict { PACKAGE_PIN F14  IOSTANDARD LVCMOS33 } [get_ports { clk }];
set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports { rst }];
set_property -dict { PACKAGE_PIN K2   IOSTANDARD LVCMOS33 } [get_ports { en }];
set_property -dict { PACKAGE_PIN K1   IOSTANDARD LVCMOS33 } [get_ports { stop }];
set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports { in[0] }];
set_property -dict { PACKAGE_PIN V2   IOSTANDARD LVCMOS33 } [get_ports { in[1] }];
set_property -dict { PACKAGE_PIN A4   IOSTANDARD LVCMOS33 } [get_ports { clk_delay }];
set_property -dict { PACKAGE_PIN B5   IOSTANDARD LVCMOS33 } [get_ports { floor_display[6] }];
set_property -dict { PACKAGE_PIN D6   IOSTANDARD LVCMOS33 } [get_ports { floor_display[5] }];
set_property -dict { PACKAGE_PIN A7   IOSTANDARD LVCMOS33 } [get_ports { floor_display[4] }];
set_property -dict { PACKAGE_PIN B7   IOSTANDARD LVCMOS33 } [get_ports { floor_display[3] }];
set_property -dict { PACKAGE_PIN A5   IOSTANDARD LVCMOS33 } [get_ports { floor_display[2] }];
set_property -dict { PACKAGE_PIN C5   IOSTANDARD LVCMOS33 } [get_ports { floor_display[1] }];
set_property -dict { PACKAGE_PIN D7   IOSTANDARD LVCMOS33 } [get_ports { floor_display[0] }];
set_property -dict { PACKAGE_PIN F2   IOSTANDARD LVCMOS33 } [get_ports { changes_count[3]}];
set_property -dict { PACKAGE_PIN F1   IOSTANDARD LVCMOS33 } [get_ports { changes_count[2]}];
set_property -dict { PACKAGE_PIN G2   IOSTANDARD LVCMOS33 } [get_ports { changes_count[1]}];
set_property -dict { PACKAGE_PIN G1   IOSTANDARD LVCMOS33 } [get_ports { changes_count[0]}];
